In [3]:
import torch 
import torch.nn as nn


In [8]:
#input

torch.manual_seed(42)
input = torch.tensor([1.0,2.0,3.0])

In [9]:
neuron = nn.Linear(in_features=3, out_features=1)

In [10]:
output = neuron(input)

In [12]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [14]:
# verify ... formula
neuron.weight @ input + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [15]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)